/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "jogo.h"


void
jogo_prog_2(char *host, int a)
{
	CLIENT *clnt;
	int  *result_1;
	num  ppt_2_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, JOGO_PROG, JOGO_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	ppt_2_arg.numero=a;
	result_1 = ppt_2(&ppt_2_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else if(*result_1 == 0)
	{
		printf("Pedra(Jogador) x Pedra(Servidor)\n");
		printf("EMPATE!!\n");

	}
	else if(*result_1 == 1)
	{
		printf("Pedra(Jogador) x Papel(Servidor)\n");
		printf("Servidor Ganhou!!\n");

	}
	else if(*result_1 == 2)
	{
		printf("Pedra(Jogador) x Tesoura(Servidor)\n");
		printf("Jogador Ganhou!!\n");

	}
	else if(*result_1 == 3)
	{
		printf("Papel(Jogador) x Pedra(Servidor)\n");
		printf("Jogador Ganhou!!\n");

	}
	else if(*result_1 == 4)
	{
		printf("Papel(Jogador) x Papel(Servidor)\n");
		printf("EMPATE!!\n");

	}
	else if(*result_1 == 5)
	{
		printf("Papel(Jogador) x Tesoura(Servidor)\n");
		printf("Servidor Ganhou!!\n");

	}
	else if(*result_1 == 6)
	{
		printf("Tesoura(Jogador) x Pedra(Servidor)\n");
		printf("Servidor Ganhou!!\n");

	}
	else if(*result_1 == 7)
	{
		printf("Tesoura(Jogador) x Papel(Servidor)\n");
		printf("Jogador Ganhou!!\n");

	}
	else if(*result_1 == 8)
	{
		printf("Tesoura(Jogador) x Tesoura(Servidor)\n");
		printf("EMPATE!!\n");

	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	char dig[10];
	if (argc < 1) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	printf("Digite sua escolha: ");
	scanf("%s", dig);
	if(dig[0] == 'p')
	{
		if(dig[1] == 'e')
		{
			jogo_prog_2 (host, 0);

		}
		else if(dig[1] == 'a')
		{
			jogo_prog_2 (host, 1);

		}
	}
	else if(dig[0] == 't')
	{
		jogo_prog_2 (host, 2);

	}
	else
	{
		printf("ERRO!");

	}
exit (0);
}
