/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _JOGO_H_RPCGEN
#define _JOGO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct num {
	int numero;
};
typedef struct num num;

#define JOGO_PROG 3213
#define JOGO_VERSION 2

#if defined(__STDC__) || defined(__cplusplus)
#define ppt 2
extern  int * ppt_2(num *, CLIENT *);
extern  int * ppt_2_svc(num *, struct svc_req *);
extern int jogo_prog_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ppt 2
extern  int * ppt_2();
extern  int * ppt_2_svc();
extern int jogo_prog_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_num (XDR *, num*);

#else /* K&R C */
extern bool_t xdr_num ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_JOGO_H_RPCGEN */
