/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "jogo.h"
#include "stdlib.h"
int *
ppt_2_svc(num *argp, struct svc_req *rqstp)
{
	static int result, pc;
	pc = rand() % 3;
	printf("Requisição recebida!\n");
	if(argp->numero == 0)
	{
		if(pc == 0)
		{
			result = 0;
			return &result;

		}
		else if(pc == 1)
		{
			result = 1;
			return &result;
			
		}
		else if(pc == 2)
		{
			result = 2;
			return &result;
			
		}


	}
	else if(argp->numero == 1)
	{
		if(pc == 0)
		{
			result = 3;
			return &result;

		}
		else if(pc == 1)
		{
			result = 4;
			return &result;
			
		}
		else if(pc == 2)
		{
			result = 5;
			return &result;
			
		}


	}
	else if(argp->numero == 2)
	{
		if(pc == 0)
		{
			result = 6;
			return &result;

		}
		else if(pc == 1)
		{
			result = 7;
			return &result;
			
		}
		else if(pc == 2)
		{
			result = 8;
			return &result;
			
		}


	}

	return &result;
}
